feat: add includeCommitId option
invertase/melos pull request #325
Opened 2022-06-17 21:14 UTC by rufman

## Description
Add the option `includeCommitId`, which prints the short commit id in
the changelog without including the link to the commit.

This allows users of git repositories that are not GitHub or GitLab to
have the commit sha present in the changelog instead of just the commit
message.

If both `includeCommitId` and `linkToCommits` are set to true, commit
linking takes presidence.

## Type of Change

- [ x] ✨ `feat` -- New feature (non-breaking change which adds functionality)
- [ ] 🛠️ `fix` -- Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ `!` -- Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 `refactor` -- Code refactor
- [ ] ✅ `ci` -- Build configuration change
- [ ] 📝 `docs` -- Documentation
- [ ] 🗑️ `chore` -- Chore

2022-06-17 21:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/invertase/melos?pullRequest=325) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/invertase/melos?pullRequest=325) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/invertase/melos?pullRequest=325) it.</sub>

2022-06-20 07:28 UTC, blaugold requested changes
Thanks for this! This looks all good. Please also document the new option [here](https://github.com/invertase/melos/blob/main/docs/configuration/overview.mdx).

2022-06-21 09:43 UTC, blaugold approved these changes
LGTM

2022-06-21 19:10 UTC, Salakar approved these changes

2022-06-21 19:16 UTC, merged